<?php

namespace Repositories;

use Indoctrinated\Repository;
use Users as Entity;

/**
 * Users
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users extends Repository
{
    public function findByLogin(
        string $account,
        string $password
    )
    {
        $user = $this->createQueryBuilder('record')
            ->andWhere('record.account = :account')
            ->andWhere('record.archivedAt IS NULL')
            ->setParameter('account', $account)
                ->getQuery()
                    ->getOneOrNullResult();
        
        if (!$user) {
            return;
        }

        if (!password_verify($password, $user->getPassword())) {
            return;
        }

        return $user;
    }
}
